// Copyright 2026 Google LLC
// SPDX-License-Identifier: Apache-2.0

// Code generated by gen_cibuildwheel_images.go. DO NOT EDIT.
// Regenerate: go generate ./pkg/rebuild/pypi/platform

package platform

import "time"

// CibuildwheelPins lists the cibuildwheel releases that pin a supported x86_64
// build image, sorted by version.
var CibuildwheelPins = CibuildwheelPinTable{
	{
		Version:   "1.4.0",
		Published: time.Date(2020, time.May, 2, 16, 57, 44, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-05-01-b37d76b"},
		},
	},
	{
		Version:   "1.4.1",
		Published: time.Date(2020, time.May, 4, 16, 12, 24, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-05-01-b37d76b"},
		},
	},
	{
		Version:   "1.4.2",
		Published: time.Date(2020, time.May, 25, 15, 17, 19, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-05-17-2f8ac3b"},
		},
	},
	{
		Version:   "1.5.0",
		Published: time.Date(2020, time.June, 24, 9, 15, 43, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-05-17-2f8ac3b"},
		},
	},
	{
		Version:   "1.5.1",
		Published: time.Date(2020, time.June, 25, 9, 54, 16, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-05-17-2f8ac3b"},
		},
	},
	{
		Version:   "1.5.2",
		Published: time.Date(2020, time.July, 8, 22, 0, 23, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-05-17-2f8ac3b"},
		},
	},
	{
		Version:   "1.5.3",
		Published: time.Date(2020, time.July, 19, 11, 0, 43, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-05-17-2f8ac3b"},
		},
	},
	{
		Version:   "1.5.4",
		Published: time.Date(2020, time.July, 19, 21, 41, 17, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-05-17-2f8ac3b"},
		},
	},
	{
		Version:   "1.5.5",
		Published: time.Date(2020, time.July, 22, 17, 58, 22, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-05-17-2f8ac3b"},
		},
	},
	{
		Version:   "1.6.0",
		Published: time.Date(2020, time.September, 9, 7, 58, 32, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-08-29-f97fd86"},
		},
	},
	{
		Version:   "1.6.1",
		Published: time.Date(2020, time.September, 20, 16, 37, 10, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-09-20-fb9af88"},
		},
	},
	{
		Version:   "1.6.2",
		Published: time.Date(2020, time.October, 9, 12, 23, 45, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-10-06-b2ca7a1"},
		},
	},
	{
		Version:   "1.6.3",
		Published: time.Date(2020, time.October, 12, 20, 6, 23, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-10-06-b2ca7a1"},
		},
	},
	{
		Version:   "1.6.4",
		Published: time.Date(2020, time.October, 31, 15, 57, 47, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-10-06-b2ca7a1"},
		},
	},
	{
		Version:   "1.7.0",
		Published: time.Date(2020, time.November, 27, 10, 17, 3, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-11-11-bc8ce45"},
		},
	},
	{
		Version:   "1.7.1",
		Published: time.Date(2020, time.December, 3, 18, 2, 53, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-11-11-bc8ce45"},
		},
	},
	{
		Version:   "1.7.2",
		Published: time.Date(2020, time.December, 21, 13, 21, 16, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-12-18-cb453dc"},
		},
	},
	{
		Version:   "1.7.3",
		Published: time.Date(2021, time.January, 1, 13, 22, 45, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-12-30-68d3257"},
		},
	},
	{
		Version:   "1.7.4",
		Published: time.Date(2021, time.January, 2, 11, 47, 35, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2020-12-30-68d3257"},
		},
	},
	{
		Version:   "1.8.0",
		Published: time.Date(2021, time.January, 22, 19, 19, 25, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-01-12-c8250d8"},
		},
	},
	{
		Version:   "1.9.0",
		Published: time.Date(2021, time.February, 5, 21, 45, 57, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-01-24-91ce2b8"},
		},
	},
	{
		Version:   "1.10.0",
		Published: time.Date(2021, time.February, 23, 21, 9, 42, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-02-20-2c345f8"},
		},
	},
	{
		Version:   "1.10.1",
		Published: time.Date(2021, time.May, 1, 17, 24, 18, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-04-05-b4fd19d"},
		},
	},
	{
		Version:   "1.11.0",
		Published: time.Date(2021, time.May, 1, 17, 25, 9, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-04-05-b4fd19d"},
		},
	},
	{
		Version:   "1.11.1",
		Published: time.Date(2021, time.May, 28, 14, 51, 30, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-05-01-28d233a", Digest: "sha256:d9a2ceb5542a1fd7f28153307fc9a5304c85e0f2b6c7da5e6a3abe74bd5652f1"},
		},
	},
	{
		Version:   "1.12.0",
		Published: time.Date(2021, time.June, 22, 17, 14, 26, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-05-01-28d233a", Digest: "sha256:d9a2ceb5542a1fd7f28153307fc9a5304c85e0f2b6c7da5e6a3abe74bd5652f1"},
		},
	},
	{
		Version:   "2.0.0",
		Published: time.Date(2021, time.July, 16, 11, 7, 8, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-07-14-67a6e11"},
		},
	},
	{
		Version:   "2.0.1",
		Published: time.Date(2021, time.July, 25, 13, 40, 43, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-07-25-cfe8a6c"},
		},
	},
	{
		Version:   "2.1.1",
		Published: time.Date(2021, time.August, 7, 19, 7, 21, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-08-03-e7edb37", Digest: "sha256:df5939d043217d4076d4703726b710c14f112ba3cbdd6c5aed9d56e1679f67c9"},
		},
	},
	{
		Version:   "2.1.2",
		Published: time.Date(2021, time.September, 14, 8, 14, 34, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-09-12-b124c44", Digest: "sha256:73d0fe86eb8345956568f8bfbf2d530dd6feee1ee262035826d395b5b1a009d0"},
		},
	},
	{
		Version:   "2.1.3",
		Published: time.Date(2021, time.October, 6, 20, 22, 27, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-10-06-94da8f1", Digest: "sha256:e1e4b08928f24f870adcf6c942498a46c25bcb1dcff8eafd934072806fd1c210"},
			ImageMusllinux1_1X86_64:  {Tag: "2021-10-06-94da8f1", Digest: "sha256:854969eb271fb04eb37661f92a0eb4261dd7c81aa2998772708e3cd6e1011b72"},
		},
	},
	{
		Version:   "2.2.0",
		Published: time.Date(2021, time.October, 26, 14, 26, 4, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-10-10-790306f", Digest: "sha256:4c4414678c423c65eb3df8d8ae73af2650e2cacfb78df9b270db8a0358a32b4f"},
			ImageMusllinux1_1X86_64:  {Tag: "2021-10-10-790306f", Digest: "sha256:b1ae3a082c9a4f689e29551e7a3f43e3cab848ef7e64bb682db84241a1dac4d6"},
		},
	},
	{
		Version:   "2.2.1",
		Published: time.Date(2021, time.October, 26, 18, 23, 26, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-10-10-790306f", Digest: "sha256:4c4414678c423c65eb3df8d8ae73af2650e2cacfb78df9b270db8a0358a32b4f"},
			ImageMusllinux1_1X86_64:  {Tag: "2021-10-10-790306f", Digest: "sha256:b1ae3a082c9a4f689e29551e7a3f43e3cab848ef7e64bb682db84241a1dac4d6"},
		},
	},
	{
		Version:   "2.2.2",
		Published: time.Date(2021, time.October, 26, 19, 38, 37, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-10-10-790306f", Digest: "sha256:4c4414678c423c65eb3df8d8ae73af2650e2cacfb78df9b270db8a0358a32b4f"},
			ImageMusllinux1_1X86_64:  {Tag: "2021-10-10-790306f", Digest: "sha256:b1ae3a082c9a4f689e29551e7a3f43e3cab848ef7e64bb682db84241a1dac4d6"},
		},
	},
	{
		Version:   "2.3.0",
		Published: time.Date(2021, time.November, 26, 18, 49, 43, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-11-20-f410d11", Digest: "sha256:9a0b5c9654cc24b29084ed98801113199ecb7e7c59713d5ff3d819534548b5a5"},
			ImageMusllinux1_1X86_64:  {Tag: "2021-11-20-f410d11", Digest: "sha256:a63cdac39aa2d877ab5d5588eece168967b026b6970f25428a8e1a1b80b5b7fa"},
		},
	},
	{
		Version:   "2.3.1",
		Published: time.Date(2021, time.December, 14, 19, 0, 30, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2021-12-12-e5100b5", Digest: "sha256:17de698632b5255a4e3c26bf2cbd4a1c2d46662130503bf9660531517621651e"},
			ImageMusllinux1_1X86_64:  {Tag: "2021-12-12-e5100b5", Digest: "sha256:0ce6cd0d4cfe73916419b8712fdda065a3a9d7e96b356daffa9d6981e677c11d"},
		},
	},
	{
		Version:   "2.4.0",
		Published: time.Date(2022, time.April, 2, 13, 56, 41, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-03-31-361e6b6", Digest: "sha256:1353b03a914b130596219199eeb80a6213dca4bdc993102945f23438adc5a882"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-03-31-361e6b6", Digest: "sha256:a9a51587b3e7a2d28954860a6406ff1f666e27396ad1d115a5793ea24a222ab0"},
		},
	},
	{
		Version:   "2.5.0",
		Published: time.Date(2022, time.April, 29, 13, 55, 25, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-04-03-da6ecb3", Digest: "sha256:9b463efac479efbcab6dec77eca28c5cfa0c5ef64f13ac184eb7117dc1f8edda"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-04-03-da6ecb3", Digest: "sha256:b4df4187c89d14ceccf5757132e2548d7963cd39476005e5b6b414a2b9583175"},
		},
	},
	{
		Version:   "2.6.0",
		Published: time.Date(2022, time.May, 25, 17, 46, 19, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-05-22-fbe07ea", Digest: "sha256:285314ad4a2fdc0f2cef58f90d8910628c3e0eeb5d1320c49c2e59bf40aa6df7"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-05-22-fbe07ea", Digest: "sha256:5120c468fd2abee7ff03fa3743fa583ea2723236c8b98c6351c05c9d6ade1def"},
		},
	},
	{
		Version:   "2.6.1",
		Published: time.Date(2022, time.June, 7, 8, 17, 47, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-06-05-61145a4", Digest: "sha256:1a9dfe7d989fc828f2921b0b8c21673d5eac6e4f9ade8ca9b93939bcbb9b8b4c"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-06-05-61145a4", Digest: "sha256:e7d218fdde354b88f5d12053b55af7c76eca70d5e7e04b68d4e3382ae1a45f8d"},
		},
	},
	{
		Version:   "2.7.0",
		Published: time.Date(2022, time.June, 17, 18, 42, 37, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-06-13-c365205", Digest: "sha256:c46615370b42a79a448fa20fc4697400d12fd2418a85a7071a3fed1a264e512e"},
			ImageManylinux2_28X86_64: {Tag: "2022-06-13-c365205", Digest: "sha256:f31a199b3945bcddb5fe2db7ae4a24c169fa479581cfbb568eab113790b3ef1b"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-06-13-c365205", Digest: "sha256:59cffe3a5c38f08aba4ea5a9cc646a4795bd630f23ce243593c370d0f57f693b"},
		},
	},
	{
		Version:   "2.8.0",
		Published: time.Date(2022, time.July, 5, 17, 36, 47, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-06-26-9a2ca4b", Digest: "sha256:9df40ad692387e3165097d2fe7b48b65fec450eb104ea48b22e4dfd9de4fb38c"},
			ImageManylinux2_28X86_64: {Tag: "2022-06-26-9a2ca4b", Digest: "sha256:c8bad257ee3f7783d2387c8297f6d99d5786417af18af0a7c1720230b3c42337"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-06-26-9a2ca4b", Digest: "sha256:76f0c67af574fe623215caa4d9882c11889f2257f179abf08421485574af3cc3"},
		},
	},
	{
		Version:   "2.8.1",
		Published: time.Date(2022, time.July, 18, 20, 44, 2, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-07-17-51324db", Digest: "sha256:2e799b2b20d156e2bc4e3a5c66ef473c176b04f798276b27c8e8f136fe2af0e1"},
			ImageManylinux2_28X86_64: {Tag: "2022-07-17-51324db", Digest: "sha256:aa9571a3b557908e388c94b310c79630d9de18a982df6c30ab99b7c41f6d1dc3"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-07-17-51324db", Digest: "sha256:1f0e4647459a11c68444e39c0ae3338d2cd23f7f799ba0b9edd149a9fe53c317"},
		},
	},
	{
		Version:   "2.9.0",
		Published: time.Date(2022, time.August, 11, 18, 45, 31, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-08-09-51a01be", Digest: "sha256:d195b4906bd74dcc9db60e8ffa594dd37f5eb7e9ce41dc1683cf9458a22ddf2e"},
			ImageManylinux2_28X86_64: {Tag: "2022-08-09-51a01be", Digest: "sha256:b0f1ba5d1a10a5ba16ba47dd46bfa87e854dde9e7b6e3b7fdca74ad033495696"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-08-09-51a01be", Digest: "sha256:d6ce0a1e31aa9e26b4947eb09565c3cdb1ff162e9f999fb21d4c078134e2094c"},
		},
	},
	{
		Version:   "2.10.0",
		Published: time.Date(2022, time.September, 13, 9, 28, 55, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-09-12-1a61614", Digest: "sha256:0e69b9fd9aaf48fc9be08c8765351d1ef1888917c68a3f777747fc7c62623bd5"},
			ImageManylinux2_28X86_64: {Tag: "2022-09-12-1a61614", Digest: "sha256:c466aef9f0a5f7d00703d53094da995871b17852ced51649b0268470fa70e843"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-09-12-1a61614", Digest: "sha256:8a45333bed8f1a12d2056de9a3d17b910737df30bd6f7a1ae4ffb7c19177894c"},
		},
	},
	{
		Version:   "2.10.1",
		Published: time.Date(2022, time.September, 18, 11, 59, 0, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-09-12-1a61614", Digest: "sha256:0e69b9fd9aaf48fc9be08c8765351d1ef1888917c68a3f777747fc7c62623bd5"},
			ImageManylinux2_28X86_64: {Tag: "2022-09-12-1a61614", Digest: "sha256:c466aef9f0a5f7d00703d53094da995871b17852ced51649b0268470fa70e843"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-09-12-1a61614", Digest: "sha256:8a45333bed8f1a12d2056de9a3d17b910737df30bd6f7a1ae4ffb7c19177894c"},
		},
	},
	{
		Version:   "2.10.2",
		Published: time.Date(2022, time.September, 25, 8, 50, 2, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-09-18-2b8b451", Digest: "sha256:69a9a654bf92c059f41e37b6c21633c11ec38040141603bbf4ea2e9bf439ab8a"},
			ImageManylinux2_28X86_64: {Tag: "2022-09-18-2b8b451", Digest: "sha256:99f01648515fdf3fb05b42c1f523f1b935876d8059d260583dd7bd855b43e111"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-09-18-2b8b451", Digest: "sha256:6e375fa43a95d12192d73c982401fe6118a9ad60b40ab9bfb51a781af916a9a9"},
		},
	},
	{
		Version:   "2.11.0",
		Published: time.Date(2022, time.October, 13, 9, 4, 15, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-10-09-941e8b2", Digest: "sha256:29188962de928569c24b869179adb9d276168230dcf770a728d72f81f78fe42d"},
			ImageManylinux2_28X86_64: {Tag: "2022-10-09-941e8b2", Digest: "sha256:32ce0af737284ba0621e4d3b876198c7a461ac728cd6d08e4718f7d069e73c31"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-10-09-941e8b2", Digest: "sha256:911f243daf9e25d91d387b1b89cddf7ed6a93b5e57a29088196a584a54bbb163"},
		},
	},
	{
		Version:   "2.11.1",
		Published: time.Date(2022, time.October, 13, 10, 46, 36, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-10-12-b8b6ebc", Digest: "sha256:f13e70d2246b65775ad272aed3d033af2e9fe6491071b96dde0e23ad23da9660"},
			ImageManylinux2_28X86_64: {Tag: "2022-10-12-b8b6ebc", Digest: "sha256:48daeae76765494ba9a225210e685efa905eb0b65c19c4b91227acb3ac4da629"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-10-12-b8b6ebc", Digest: "sha256:68b87f43fb437184807d7ebeeeb9d9c2b7250d00a8658151d8fd84f13f36076b"},
		},
	},
	{
		Version:   "2.11.2",
		Published: time.Date(2022, time.October, 26, 19, 5, 30, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-10-25-fbea779", Digest: "sha256:166d4b4db6f163f2d7a2bfbef515239910f3eab7d93be38e620fe5fdeb682f42"},
			ImageManylinux2_28X86_64: {Tag: "2022-10-25-fbea779", Digest: "sha256:7e0d90fee70d2b1c29894a0858e9f7ab7f337cff1479053789fce10c81220d58"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-10-25-fbea779", Digest: "sha256:de570e92d83360379de3fc38332ba02fddb4ac68f8cee7236d6fecbc7c5bac5e"},
		},
	},
	{
		Version:   "2.11.3",
		Published: time.Date(2022, time.December, 5, 21, 31, 21, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-11-27-b2d7fda", Digest: "sha256:d218f9d91d3ad0707354d09a5bf17f7d5ef8ff41e89073de16d9ed7f984fd9af"},
			ImageManylinux2_28X86_64: {Tag: "2022-11-27-b2d7fda", Digest: "sha256:3348f388873e8e5629ba100a06f6f27438a4227ab2607ed90df0464b1f6d801d"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-11-27-b2d7fda", Digest: "sha256:398d1a442278bbb10e77d934f17ab82555c5651c355f588786e56373a7ab78b3"},
		},
	},
	{
		Version:   "2.11.4",
		Published: time.Date(2022, time.December, 24, 15, 30, 31, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2022-12-11-145d107", Digest: "sha256:54c66a6865280a601b3888601b741e3a1c362ef8ef5d969118a22275ea225102"},
			ImageManylinux2_28X86_64: {Tag: "2022-12-11-145d107", Digest: "sha256:6518d997c29c8f8ab63e629ec2f7f0ff19ceae4ac7e818251fe439e266d9af17"},
			ImageMusllinux1_1X86_64:  {Tag: "2022-12-11-145d107", Digest: "sha256:097515617023d3198045f552a1d2f845bef822290da1e67ca8fcea4dc042c677"},
		},
	},
	{
		Version:   "2.12.0",
		Published: time.Date(2023, time.January, 16, 18, 37, 36, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2023-01-14-103cb93", Digest: "sha256:58634594f47a3180f1f54531e55033443562deb590a4af7aed583451ee29242a"},
			ImageManylinux2_28X86_64: {Tag: "2023-01-14-103cb93", Digest: "sha256:95a5d0724e6a54cadca6a428557959241cef3b5da17368ef482fa4be57580a6d"},
			ImageMusllinux1_1X86_64:  {Tag: "2023-01-14-103cb93", Digest: "sha256:e41500d888de80e0e707f1e5c4567a730f8339037664ddcb3dd81d5f1e2dc09b"},
		},
	},
	{
		Version:   "2.12.1",
		Published: time.Date(2023, time.March, 11, 13, 24, 36, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2023-03-05-271004f", Digest: "sha256:622daa4e560c2d4926920921d2e48aa276e56493787217e55734f6c64cb51b56"},
			ImageManylinux2_28X86_64: {Tag: "2023-03-05-271004f", Digest: "sha256:217e196d2a46cab6d9d3aa366a228afdb85ed8340841af05f97559b3f2aaee46"},
			ImageMusllinux1_1X86_64:  {Tag: "2023-03-05-271004f", Digest: "sha256:a0d4fb18ebbbe1735286af6d1686b8037125ef38e77d9e5e72b2472172e7029c"},
		},
	},
	{
		Version:   "2.12.2",
		Published: time.Date(2023, time.April, 18, 20, 13, 32, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2023-04-16-157f52a", Digest: "sha256:bc1b92cee27af8cd949e6abb7036ec17e2ce66066a89131fdf6ec9212c6762e3"},
			ImageManylinux2_28X86_64: {Tag: "2023-04-16-157f52a", Digest: "sha256:47e39e011cbd73378e020e4804adbb40621d26cd1e710679d0b3be8e8963f092"},
			ImageMusllinux1_1X86_64:  {Tag: "2023-04-16-157f52a", Digest: "sha256:c6dd69280dd118d3d58c2f0907421e810b0d94f0ce98032a95f7618d94c1bd53"},
		},
	},
	{
		Version:   "2.12.3",
		Published: time.Date(2023, time.April, 19, 8, 2, 51, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2023-04-16-157f52a", Digest: "sha256:bc1b92cee27af8cd949e6abb7036ec17e2ce66066a89131fdf6ec9212c6762e3"},
			ImageManylinux2_28X86_64: {Tag: "2023-04-16-157f52a", Digest: "sha256:47e39e011cbd73378e020e4804adbb40621d26cd1e710679d0b3be8e8963f092"},
			ImageMusllinux1_1X86_64:  {Tag: "2023-04-16-157f52a", Digest: "sha256:c6dd69280dd118d3d58c2f0907421e810b0d94f0ce98032a95f7618d94c1bd53"},
		},
	},
	{
		Version:   "2.13.0",
		Published: time.Date(2023, time.May, 28, 16, 5, 53, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2023-05-24-3bf828e", Digest: "sha256:181676656e7c12ac1fe3347f5260e0e980fb227d1dbe21733f56a6f6845a789f"},
			ImageManylinux2_28X86_64: {Tag: "2023-05-24-3bf828e", Digest: "sha256:1a0df55fac57910c908fe54728709dcdadb9163dd1eec85f1302b820c83c45b3"},
			ImageMusllinux1_1X86_64:  {Tag: "2023-05-24-3bf828e", Digest: "sha256:a46f73f66aa7be45d95b56bc5cea86d8d7e83acaa9ade2a6b1d23e88ce75be32"},
		},
	},
	{
		Version:   "2.13.1",
		Published: time.Date(2023, time.June, 10, 12, 23, 48, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2023-06-08-775c518", Digest: "sha256:aa23bf326064d6c87869fc9e9fcc8649bbb27043da44144f53e3730009021e00"},
			ImageManylinux2_28X86_64: {Tag: "2023-06-08-775c518", Digest: "sha256:9c068f39e91b7dc1f0e6e729f7eeeb341bb4e394368ad283cb10f456025875d0"},
			ImageMusllinux1_1X86_64:  {Tag: "2023-06-08-775c518", Digest: "sha256:b068b8a545ceee73e4255b373495e1d8a27faacb48be2b47b5d09ab96c112aab"},
		},
	},
	{
		Version:   "2.14.0",
		Published: time.Date(2023, time.July, 10, 10, 45, 21, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2023-07-06-73b0312", Digest: "sha256:a69b757e023588080bb06182b53b3dc32403617de2f806b7c76b48a9d9c624f0"},
			ImageManylinux2_28X86_64: {Tag: "2023-07-06-73b0312", Digest: "sha256:9f6e5bd684cebfbb39236fa88789f541bb282c902bace39608fd1adec188e17e"},
			ImageMusllinux1_1X86_64:  {Tag: "2023-07-06-73b0312", Digest: "sha256:a4594dcb569b0a485999c2010c013f46205771702bac36a45cd1ec3fc6b37f53"},
		},
	},
	{
		Version:   "2.14.1",
		Published: time.Date(2023, time.July, 15, 8, 55, 2, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2023-07-14-55e4124", Digest: "sha256:eab4c20f80c8aeb758ccfb4cd235c9d168adb02cac83b085f0aec64101d5bdf2"},
			ImageManylinux2_28X86_64: {Tag: "2023-07-14-55e4124", Digest: "sha256:56f72975078d5abf0d719606779fa8fbd797910b2bd532797c8bf3204213a14a"},
			ImageMusllinux1_1X86_64:  {Tag: "2023-07-14-55e4124", Digest: "sha256:98fa5374d712ee23863f322022097340156a3858df736aee76b422b5b6540a16"},
		},
	},
	{
		Version:   "2.15.0",
		Published: time.Date(2023, time.August, 8, 18, 2, 29, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2023-08-07-e3f636d", Digest: "sha256:6b61fd1ad2cb7c0c409a037663b7289201ed2570db7076842f3a34459398c8ab"},
			ImageManylinux2_28X86_64: {Tag: "2023-08-07-e3f636d", Digest: "sha256:9bb08d82445bca364cb7f0b73e64464fefdd5ac10f13418883c156cb9557dde5"},
			ImageMusllinux1_1X86_64:  {Tag: "2023-08-07-e3f636d", Digest: "sha256:2febd6e70eed9e74df31e5f3967be96d3d2776fd891e2347d71abcd6d3b301d3"},
			ImageMusllinux1_2X86_64:  {Tag: "2023-08-07-e3f636d", Digest: "sha256:38d4ab40a8142a3c8b0ac765da14d5feae823f1671e9edc376bc5cb7222539c4"},
		},
	},
	{
		Version:   "2.16.0",
		Published: time.Date(2023, time.September, 18, 17, 48, 4, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2023-09-17-ae90a16", Digest: "sha256:1daa7e6160cc707c2db44708b756fe18c163cd8ab70f76d4a23432b3c6a5b45d"},
			ImageManylinux2_28X86_64: {Tag: "2023-09-17-ae90a16", Digest: "sha256:bde3ffb0694a8359dce3558e17e18be08151c1e6cecac101c19ae5721938cc7f"},
			ImageMusllinux1_1X86_64:  {Tag: "2023-09-17-ae90a16", Digest: "sha256:35eecf24a7d01e1a79d215641f891f2da4dfbf393941eb24a3fa050408a4fc3b"},
			ImageMusllinux1_2X86_64:  {Tag: "2023-09-17-ae90a16", Digest: "sha256:391af1a54511ce3c86f4ba308c1571b3e242a39c386b4d376670e35adcca9926"},
		},
	},
	{
		Version:   "2.16.1",
		Published: time.Date(2023, time.September, 26, 8, 53, 50, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2023-09-24-36b93e4", Digest: "sha256:07145d872015f593222ac57874e0ef14f3f4bde5b391ff4d1be8979c28170d7e"},
			ImageManylinux2_28X86_64: {Tag: "2023-09-24-36b93e4", Digest: "sha256:69166ba72e6905c00ea2857c2f98e14d20dbb5c89c6627fdaa2ca78639c601c9"},
			ImageMusllinux1_1X86_64:  {Tag: "2023-09-24-36b93e4", Digest: "sha256:f44e679c6454ce9dca00bd6d0a0fdd6180c476cb309ea6e41d8c476b8b555478"},
			ImageMusllinux1_2X86_64:  {Tag: "2023-09-24-36b93e4", Digest: "sha256:19eb69bb43891953dea4dfb63c7b0530292f2a37c1fc7eb65bd57306a9289602"},
		},
	},
	{
		Version:   "2.16.2",
		Published: time.Date(2023, time.October, 3, 19, 9, 31, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2023-10-03-72cdc42", Digest: "sha256:29ae5cc1fbe9c6cc65cfb83148a7ccdaa5ecac8134cb94ed3722738c6851a0f1"},
			ImageManylinux2_28X86_64: {Tag: "2023-10-03-72cdc42", Digest: "sha256:c7a9015a36cae1a31bc6aa551b77ea366c9f42445c95d0dfe25a20782d361457"},
			ImageMusllinux1_1X86_64:  {Tag: "2023-10-03-72cdc42", Digest: "sha256:26209e77323397c83632e9ae21928882b148ad5e669a04b6601176f667e35b0e"},
			ImageMusllinux1_2X86_64:  {Tag: "2023-10-03-72cdc42", Digest: "sha256:1d514c413ac44547fa1511e7171be37d7a28fe1326141b994eada66e1e4a8557"},
		},
	},
	{
		Version:   "2.16.3",
		Published: time.Date(2024, time.January, 26, 19, 23, 34, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2024-01-08-eb135ed", Digest: "sha256:460f6d2125c112e8b1a5fa413673e2e58322f05ff996255cada0ec9bd8347111"},
			ImageManylinux2_28X86_64: {Tag: "2024-01-08-eb135ed", Digest: "sha256:f2c9024c753f7dcec93900cae8815ca4f1e47178d435c42b98a21b633a1028eb"},
			ImageMusllinux1_1X86_64:  {Tag: "2024-01-08-eb135ed", Digest: "sha256:8ff1a2c54e73ac91a327b72c8acafacc59d415f1c66bace4933c719d4cbf61f5"},
			ImageMusllinux1_2X86_64:  {Tag: "2024-01-08-eb135ed", Digest: "sha256:9b3d2e3369f91091237f334f022562acdc01405df6de6dc80736cd9682d234cc"},
		},
	},
	{
		Version:   "2.16.4",
		Published: time.Date(2024, time.January, 28, 17, 23, 44, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2024-01-23-12ffabc", Digest: "sha256:6200507e50ec3f20ef1874d2b3d0f8edbaf1ecfd5a65dac1178b82faf6a8eed4"},
			ImageManylinux2_28X86_64: {Tag: "2024-01-23-12ffabc", Digest: "sha256:ed8e07fb14ad078baf84d96d6e159d833684b4a56ca9d639eb1b5a94fd7a5361"},
			ImageMusllinux1_1X86_64:  {Tag: "2024-01-23-12ffabc", Digest: "sha256:755c8471cad556d399f729fe574453b743d53d1b85074a23dd5ebdeacf6c1b50"},
			ImageMusllinux1_2X86_64:  {Tag: "2024-01-23-12ffabc", Digest: "sha256:5b583a5c6a649f407fb60afbbb31c1fd364396414d009211845202e0e4e24ce6"},
		},
	},
	{
		Version:   "2.16.5",
		Published: time.Date(2024, time.January, 30, 23, 16, 11, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2024-01-23-12ffabc", Digest: "sha256:6200507e50ec3f20ef1874d2b3d0f8edbaf1ecfd5a65dac1178b82faf6a8eed4"},
			ImageManylinux2_28X86_64: {Tag: "2024-01-23-12ffabc", Digest: "sha256:ed8e07fb14ad078baf84d96d6e159d833684b4a56ca9d639eb1b5a94fd7a5361"},
			ImageMusllinux1_1X86_64:  {Tag: "2024-01-23-12ffabc", Digest: "sha256:755c8471cad556d399f729fe574453b743d53d1b85074a23dd5ebdeacf6c1b50"},
			ImageMusllinux1_2X86_64:  {Tag: "2024-01-23-12ffabc", Digest: "sha256:5b583a5c6a649f407fb60afbbb31c1fd364396414d009211845202e0e4e24ce6"},
		},
	},
	{
		Version:   "2.17.0",
		Published: time.Date(2024, time.March, 11, 21, 22, 5, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2024-03-10-4935fcc", Digest: "sha256:36addcca8e9fb11f106ccb7fb61fc9bfc44aa407ce82e7fa3762deedc696cf59"},
			ImageManylinux2_28X86_64: {Tag: "2024-03-10-4935fcc", Digest: "sha256:b4c1a31a186b3b08f3d9ed7e7d999297abc4d3291944839fe7a9d88aa642cba9"},
			ImageMusllinux1_1X86_64:  {Tag: "2024-03-10-4935fcc", Digest: "sha256:f0fae2381d9cb6270fd9210cde60d05c8939f1b9a6de08427bf0ec818fac8b38"},
			ImageMusllinux1_2X86_64:  {Tag: "2024-03-10-4935fcc", Digest: "sha256:e32adbfbc72570d59a07e951c0d699f9fa59618801ca6857d5cf8dfece8bf5a2"},
		},
	},
	{
		Version:   "2.18.0",
		Published: time.Date(2024, time.May, 12, 4, 19, 43, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2024-05-10-7415d48", Digest: "sha256:69db66df471ef1431daf4bcbd625a563dc88281d11cc3e5389781ed6ca908529"},
			ImageManylinux2_28X86_64: {Tag: "2024-05-10-7415d48", Digest: "sha256:b303c44dbb17b6e17783e35661e898eb7a4a6515f96712e88f1e123ba992634e"},
			ImageMusllinux1_1X86_64:  {Tag: "2024-05-10-7415d48", Digest: "sha256:9caa77da6bca1e1a2f3a019ba9e819a1f389d53a0b3a4e9a7b39c68d77ca5325"},
			ImageMusllinux1_2X86_64:  {Tag: "2024-05-10-7415d48", Digest: "sha256:fe053a2ff77a8e544e155bd75272953afc0006a9456b714974c84c1d4ce0fcc1"},
		},
	},
	{
		Version:   "2.18.1",
		Published: time.Date(2024, time.May, 20, 11, 25, 5, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2024-05-13-0983f6f", Digest: "sha256:b31275b340d8661e45a9eed29ca93d605a702557781fa65a7cb35bc9639165ad"},
			ImageManylinux2_28X86_64: {Tag: "2024-05-13-0983f6f", Digest: "sha256:229d0e2a9faf7e99f3ee452f433eb1bab9a0195a5258230162fa35934e85a159"},
			ImageMusllinux1_1X86_64:  {Tag: "2024-05-13-0983f6f", Digest: "sha256:d26b70590029a5cc1dffd68846c1f0ecc9c80187c6b2f8029e737ae934c05b04"},
			ImageMusllinux1_2X86_64:  {Tag: "2024-05-13-0983f6f", Digest: "sha256:399e4d12030f562619c20b4eb8ba87ab17017f190896601edc201ff21226decb"},
		},
	},
	{
		Version:   "2.19.0",
		Published: time.Date(2024, time.June, 10, 15, 30, 24, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2024-06-06-99f15a7", Digest: "sha256:32062dc73ac000e96b98adfa067a77245390a806a3e1c7851e820ddf66f6b951"},
			ImageManylinux2_28X86_64: {Tag: "2024-06-06-99f15a7", Digest: "sha256:099d778b4fd931190dbc5f38e0035c9fefc69dd26c58d25bb4fae22f51acfd47"},
			ImageMusllinux1_1X86_64:  {Tag: "2024-06-06-99f15a7", Digest: "sha256:ab93e08ae328d025f7c74d529e9140a95c294d09864ae157af8e20826d5a0c22"},
			ImageMusllinux1_2X86_64:  {Tag: "2024-06-06-99f15a7", Digest: "sha256:c1234989e24cd34c6407ff57f208961ecf822aa8c287a82fb11ef4be8033c8b2"},
		},
	},
	{
		Version:   "2.19.1",
		Published: time.Date(2024, time.June, 13, 6, 40, 28, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2024.06.12-1", Digest: "sha256:727a9a46ae1052fc28f8dfee8ab2bc3c5f283914ab39c1f13fa4a3016ba067d9"},
			ImageManylinux2_28X86_64: {Tag: "2024.06.12-1", Digest: "sha256:39bb36d186e76e19438626f9dd2a06c0edb1ec71e69377694be3f97ad227f364"},
			ImageMusllinux1_1X86_64:  {Tag: "2024.06.12-1", Digest: "sha256:2eb9ae9fd974ab9a173e87c7b3e58cd1f1c6e7ad5135dee73ca33698b478e163"},
			ImageMusllinux1_2X86_64:  {Tag: "2024.06.12-1", Digest: "sha256:989a1f5abb562ca7c4d0468f9c19d17f7ffd75e944b685d3d569162f0a52a434"},
		},
	},
	{
		Version:   "2.19.2",
		Published: time.Date(2024, time.July, 2, 12, 11, 10, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2024.07.02-0", Digest: "sha256:b8a442f00c20eaf830f45ccef3f21e12b561238e2af61abffca014f3a34590f6"},
			ImageManylinux2_28X86_64: {Tag: "2024.07.02-0", Digest: "sha256:1e365067728237f3634303b1da88b605a683b573c169ff8fd2889d25ee6acbca"},
			ImageMusllinux1_1X86_64:  {Tag: "2024.07.02-0", Digest: "sha256:c4b3591352878ac58b5968b954ea20c02dca88916aaf960f7eabaa31d34dd2dd"},
			ImageMusllinux1_2X86_64:  {Tag: "2024.07.02-0", Digest: "sha256:1c91bccc98a2d4f4b95746ce9e4d13abe89c63d0a8de89ff43201869a8531819"},
		},
	},
	{
		Version:   "2.20.0",
		Published: time.Date(2024, time.August, 4, 2, 41, 16, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2024.08.03-1", Digest: "sha256:e620e1be73a5cc9aa8fbefa17faf545b61aa9417887030dae568db2137cb19b4"},
			ImageManylinux2_28X86_64: {Tag: "2024.08.03-1", Digest: "sha256:cd227b85f0b2a12a509ae9f674e9bd87a82abf51a10b973e9eaa495f8b441c0a"},
			ImageMusllinux1_1X86_64:  {Tag: "2024.08.03-1", Digest: "sha256:63a798866c56435aa50a8766b6b488c9e980f028cba5e9417c34f875478f8108"},
			ImageMusllinux1_2X86_64:  {Tag: "2024.08.03-1", Digest: "sha256:9b0904071dd4e1e0f37bf85d3b439d3757edbb340b670f82239e33b40028b739"},
		},
	},
	{
		Version:   "2.21.0",
		Published: time.Date(2024, time.September, 13, 15, 44, 57, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2024.09.09-0", Digest: "sha256:f9274ea3d460654640130caf07dd331c011289c1812b5cfdbad5e360576012a0"},
			ImageManylinux2_28X86_64: {Tag: "2024.09.09-0", Digest: "sha256:f61937a94c402eaf53dc5ab140eae1fa447123001569178e3fd880c68b120cbd"},
			ImageMusllinux1_1X86_64:  {Tag: "2024.09.09-0", Digest: "sha256:b7bb1a40717a778be17e19ae59798e5c06b4068cd9c59352bbf7b442fa9188e1"},
			ImageMusllinux1_2X86_64:  {Tag: "2024.09.09-0", Digest: "sha256:e8cd1205b686221efcae41d219db05b1db5ca8e6374fbfa588d32176574b26a4"},
		},
	},
	{
		Version:   "2.21.1",
		Published: time.Date(2024, time.September, 17, 1, 7, 23, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2024.09.16-1", Digest: "sha256:03fe2852d50daf4d8329fe65ff187603e7a90c4e2f326014cecbc323f8f2d2bf"},
			ImageManylinux2_28X86_64: {Tag: "2024.09.16-1", Digest: "sha256:cad96401be220094685dcaa1d032e5071cfe69446327dcf1f8534b72e374e0bb"},
			ImageMusllinux1_1X86_64:  {Tag: "2024.09.16-1", Digest: "sha256:aa2a3c8d3cb06da6b81c0c396bec42c914b6f3d00e650e363d4648652e04bf4b"},
			ImageMusllinux1_2X86_64:  {Tag: "2024.09.16-1", Digest: "sha256:9c27e9096c176a37bc3e99dc565f21410102f9d4c19e1abe4d129d18dd061956"},
		},
	},
	{
		Version:   "2.21.2",
		Published: time.Date(2024, time.October, 2, 21, 53, 47, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2024.10.01-1", Digest: "sha256:2ee3e1329ba3e85d783a4128b755803a2c7f7a42a5454464cc325df29e254b9e"},
			ImageManylinux2_28X86_64: {Tag: "2024.10.01-1", Digest: "sha256:cea0ade79068b36deae7eb7a04b4192e5ba2761d045ba5a92ba36eb5ce5f88b6"},
			ImageMusllinux1_1X86_64:  {Tag: "2024.10.01-1", Digest: "sha256:91cc54ce463bd5d28b20267afe769fcbf16fccf97482ed4f497d9e41fb59a33b"},
			ImageMusllinux1_2X86_64:  {Tag: "2024.10.01-1", Digest: "sha256:f2c9ce971946fe218622c5f0ccb1437a0ed8d4ef96d68cd43bdbc42eba500713"},
		},
	},
	{
		Version:   "2.21.3",
		Published: time.Date(2024, time.October, 9, 8, 7, 5, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2024.10.07-1", Digest: "sha256:41269ff9c2edb74de6fe65eb8c9db2b5e03370ce7f3da313aa7e3134c9371892"},
			ImageManylinux2_28X86_64: {Tag: "2024.10.07-1", Digest: "sha256:7251f50cc3380767a79044762bc13a9089b4905c15c9600335c63eb90c0a8284"},
			ImageMusllinux1_1X86_64:  {Tag: "2024.10.07-1", Digest: "sha256:ce0700c16b46b2bd2ae5e4c39b131c075da03e8cf84da0b7076fbf24a51057b6"},
			ImageMusllinux1_2X86_64:  {Tag: "2024.10.07-1", Digest: "sha256:a59f57b04f6f1204c15fc39c081bd7167af1870f32080da9f1d2084d4ead9715"},
		},
	},
	{
		Version:   "2.22.0",
		Published: time.Date(2024, time.November, 23, 6, 47, 7, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2024.11.16-1", Digest: "sha256:f09bf382e4bcbd5b3cab130f8d0f12dbe474833f95f54182e80e8c0aaa269ff0"},
			ImageManylinux2_28X86_64: {Tag: "2024.11.16-1", Digest: "sha256:2b65d3c9b6c04b1af69df6786e2a4da894df0b5ad55f68bae97b005e3b11a3c9"},
			ImageMusllinux1_1X86_64:  {Tag: "2024.10.26-1", Digest: "sha256:79908067ecc89a594474c799331ca1ef27ae36bda08960aca5a9a31c28453ef1"},
			ImageMusllinux1_2X86_64:  {Tag: "2024.11.16-1", Digest: "sha256:a84af7e4036781ef127cc87f92e8fd80de8d428e5cfaa574e48dc334bc123b9a"},
		},
	},
	{
		Version:   "2.23.0",
		Published: time.Date(2025, time.March, 1, 13, 29, 31, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2025.02.28-1", Digest: "sha256:a6d4a35895e0a5bec65b8192952b26c8bd46df9f048115884bb9ac80a3b7e663"},
			ImageManylinux2_28X86_64: {Tag: "2025.02.28-1", Digest: "sha256:2b290a5caa6d2590dbf35461ac5607dc6d658a2246a9e962211b189210132418"},
			ImageMusllinux1_1X86_64:  {Tag: "2024.10.26-1", Digest: "sha256:79908067ecc89a594474c799331ca1ef27ae36bda08960aca5a9a31c28453ef1"},
			ImageMusllinux1_2X86_64:  {Tag: "2025.02.28-1", Digest: "sha256:0ae9a3a73db74ee0253d006c4f2f7108c0f5e6a34fbfb39ed1c1a2171eb62063"},
		},
	},
	{
		Version:   "2.23.1",
		Published: time.Date(2025, time.March, 15, 18, 0, 18, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2025.03.09-1", Digest: "sha256:d53d16c5e3534f96ec749666aeba593d6498107e80c0cbf161b9163cce356297"},
			ImageManylinux2_28X86_64: {Tag: "2025.03.09-1", Digest: "sha256:bdcd177f75d8b9d5a0a3d017b69d83d8b97cdaed92ca7caf0f9605bb429c5d07"},
			ImageMusllinux1_1X86_64:  {Tag: "2024.10.26-1", Digest: "sha256:79908067ecc89a594474c799331ca1ef27ae36bda08960aca5a9a31c28453ef1"},
			ImageMusllinux1_2X86_64:  {Tag: "2025.03.09-1", Digest: "sha256:2e719b66fc7055e958bb4a10d0d9dc831d8da398170be3d658197413d38dfc70"},
		},
	},
	{
		Version:   "2.23.2",
		Published: time.Date(2025, time.March, 24, 21, 26, 55, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2025.03.23-1", Digest: "sha256:ae4cea7cb06942a2fce1aa244ca568fe10ac6d9aab97c30158cf9aae0ce5e626"},
			ImageManylinux2_28X86_64: {Tag: "2025.03.23-1", Digest: "sha256:7f7c6db512db86a6a559d5863107004004f53f369e371cdaefce47f8bda0bc2a"},
			ImageMusllinux1_1X86_64:  {Tag: "2024.10.26-1", Digest: "sha256:79908067ecc89a594474c799331ca1ef27ae36bda08960aca5a9a31c28453ef1"},
			ImageMusllinux1_2X86_64:  {Tag: "2025.03.23-1", Digest: "sha256:5ae7bf81f141c2497d49eb9662720bf0413a3474b3a172ad6ca098c2312f030b"},
		},
	},
	{
		Version:   "2.23.3",
		Published: time.Date(2025, time.April, 26, 10, 41, 26, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2025.04.19-1", Digest: "sha256:df319a1a2a0b67fabde721e7a2008ad16257e348172cc0a29d0f1f09b82f1aa8"},
			ImageManylinux2_28X86_64: {Tag: "2025.04.19-1", Digest: "sha256:7d89e036b9493f94a0bb252c1db4ab3f71f5b83874cb274f85b3c40be712f513"},
			ImageMusllinux1_1X86_64:  {Tag: "2024.10.26-1", Digest: "sha256:79908067ecc89a594474c799331ca1ef27ae36bda08960aca5a9a31c28453ef1"},
			ImageMusllinux1_2X86_64:  {Tag: "2025.04.19-1", Digest: "sha256:37645a6deff8f81eabf7e709c719f4ef2d11182e10997593d2f9f7d2dd9864cd"},
		},
	},
	{
		Version:   "2.23.4",
		Published: time.Date(2026, time.March, 16, 19, 33, 12, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2025.04.19-1", Digest: "sha256:df319a1a2a0b67fabde721e7a2008ad16257e348172cc0a29d0f1f09b82f1aa8"},
			ImageManylinux2_28X86_64: {Tag: "2025.04.19-1", Digest: "sha256:7d89e036b9493f94a0bb252c1db4ab3f71f5b83874cb274f85b3c40be712f513"},
			ImageMusllinux1_1X86_64:  {Tag: "2024.10.26-1", Digest: "sha256:79908067ecc89a594474c799331ca1ef27ae36bda08960aca5a9a31c28453ef1"},
			ImageMusllinux1_2X86_64:  {Tag: "2025.04.19-1", Digest: "sha256:37645a6deff8f81eabf7e709c719f4ef2d11182e10997593d2f9f7d2dd9864cd"},
		},
	},
	{
		Version:   "3.0.0",
		Published: time.Date(2025, time.June, 11, 13, 4, 19, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2025.06.08-1", Digest: "sha256:a33d2f70613db89bebc38cde8a9d71c0c1083b2f5491ec459e2ed5b9e1109dd4"},
			ImageManylinux2_28X86_64: {Tag: "2025.06.08-1", Digest: "sha256:634656edbdeb07f955667e645762ad218eefe25f0d185fef913221855d610456"},
			ImageManylinux2_34X86_64: {Tag: "2025.06.08-1", Digest: "sha256:48b10b46c6fc947a2727e2ce9d6fd962888f304d5838a590b80017a61a6544b6"},
			ImageMusllinux1_2X86_64:  {Tag: "2025.06.08-1", Digest: "sha256:e66ec65cd45c979d8f7ff6e0edba5baf22e569c9fc8bc6d69fe0bb44ad23d2f2"},
		},
	},
	{
		Version:   "3.0.1",
		Published: time.Date(2025, time.July, 5, 18, 5, 7, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2025.06.28-1", Digest: "sha256:a9e1411b26964ac583e6ea7d2cda8c0f21bef7d21467b44bb0cf09eda595f330"},
			ImageManylinux2_28X86_64: {Tag: "2025.06.28-1", Digest: "sha256:e45ada24fb90cb1b76ce05278c65cfffa702417972e2b0bdc4b167449ee90f30"},
			ImageManylinux2_34X86_64: {Tag: "2025.06.28-1", Digest: "sha256:8b2bd93be30b605b4bb12d6bced3782a764455418ed8b1b0639a4377095c6541"},
			ImageMusllinux1_2X86_64:  {Tag: "2025.06.28-1", Digest: "sha256:b78e940e32a2462afa953a24f8d14a1ec6549656aea9a031fd1a0b004d750815"},
		},
	},
	{
		Version:   "3.1.0",
		Published: time.Date(2025, time.July, 24, 3, 26, 11, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2025.07.23-1", Digest: "sha256:d66a118343a8421702886c2d1b08ebbd9818949df4b794b8729c40ac10a0f4b7"},
			ImageManylinux2_28X86_64: {Tag: "2025.07.23-1", Digest: "sha256:cf1b54c269252d059b204da9a98aed5c7e95c42b5bc5309ec3cb1a91ed4ec02e"},
			ImageManylinux2_34X86_64: {Tag: "2025.07.23-1", Digest: "sha256:af092c31866e8718203e32a02604134ed53c8a9783ad8cb92147ad3d19fd0088"},
			ImageMusllinux1_2X86_64:  {Tag: "2025.07.23-1", Digest: "sha256:34ac20d281385f525a985003330d1e45a3c08740228dab98207a75ea981c4b38"},
		},
	},
	{
		Version:   "3.1.1",
		Published: time.Date(2025, time.July, 24, 18, 15, 32, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2025.07.23-1", Digest: "sha256:d66a118343a8421702886c2d1b08ebbd9818949df4b794b8729c40ac10a0f4b7"},
			ImageManylinux2_28X86_64: {Tag: "2025.07.23-1", Digest: "sha256:cf1b54c269252d059b204da9a98aed5c7e95c42b5bc5309ec3cb1a91ed4ec02e"},
			ImageManylinux2_34X86_64: {Tag: "2025.07.23-1", Digest: "sha256:af092c31866e8718203e32a02604134ed53c8a9783ad8cb92147ad3d19fd0088"},
			ImageMusllinux1_2X86_64:  {Tag: "2025.07.23-1", Digest: "sha256:34ac20d281385f525a985003330d1e45a3c08740228dab98207a75ea981c4b38"},
		},
	},
	{
		Version:   "3.1.2",
		Published: time.Date(2025, time.July, 29, 15, 14, 27, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2025.07.27-1", Digest: "sha256:f1041b88ad5389065615a32fb4a59fcb39cc25c3cfee7a83273c04d68e312ea9"},
			ImageManylinux2_28X86_64: {Tag: "2025.07.27-1", Digest: "sha256:b612e4b8890ee77894f3b0337a668ca7ffbb4014ab0554ba97a1e6795e329008"},
			ImageManylinux2_34X86_64: {Tag: "2025.07.27-1", Digest: "sha256:b64beef1d067ef23073c87aef5b06d56bcef498e57475206ff1fdc3d54817234"},
			ImageMusllinux1_2X86_64:  {Tag: "2025.07.27-1", Digest: "sha256:cc980f4c2901f177b541303b392200e7144fbabcab36d78b80bdcc2c5c9cf331"},
		},
	},
	{
		Version:   "3.1.3",
		Published: time.Date(2025, time.August, 1, 16, 41, 21, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2025.07.27-1", Digest: "sha256:f1041b88ad5389065615a32fb4a59fcb39cc25c3cfee7a83273c04d68e312ea9"},
			ImageManylinux2_28X86_64: {Tag: "2025.07.27-1", Digest: "sha256:b612e4b8890ee77894f3b0337a668ca7ffbb4014ab0554ba97a1e6795e329008"},
			ImageManylinux2_34X86_64: {Tag: "2025.07.27-1", Digest: "sha256:b64beef1d067ef23073c87aef5b06d56bcef498e57475206ff1fdc3d54817234"},
			ImageMusllinux1_2X86_64:  {Tag: "2025.07.27-1", Digest: "sha256:cc980f4c2901f177b541303b392200e7144fbabcab36d78b80bdcc2c5c9cf331"},
		},
	},
	{
		Version:   "3.1.4",
		Published: time.Date(2025, time.August, 19, 18, 22, 49, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2025.08.15-1", Digest: "sha256:265279207916439ab59f696e168b579f789d1b247aa7654efa31b75416adaefa"},
			ImageManylinux2_28X86_64: {Tag: "2025.08.15-1", Digest: "sha256:6f42f4382bc73e9584206e6722e001922c0d4846c932fccaa04c0e35903b717d"},
			ImageManylinux2_34X86_64: {Tag: "2025.08.15-1", Digest: "sha256:e6e25cbad02d0ea67e9c56656493097eef389d9dac3863500f33f21a92f991f8"},
			ImageMusllinux1_2X86_64:  {Tag: "2025.08.15-1", Digest: "sha256:a169bc3a312427fcf9f3ec60ed6127ee7ccbfe6db037f06a32733570d8e230ee"},
		},
	},
	{
		Version:   "3.2.0",
		Published: time.Date(2025, time.September, 22, 20, 46, 22, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2025.09.19-1", Digest: "sha256:847f0f664e4957a2d198e84a7a41c21520b3793b9ee77dbeb0a566370239f502"},
			ImageManylinux2_28X86_64: {Tag: "2025.09.19-1", Digest: "sha256:4b44be10c57660fcf31f3cf53f47fec07f2886b535493bbdb7397ad109d4d549"},
			ImageManylinux2_34X86_64: {Tag: "2025.09.19-1", Digest: "sha256:c4e44def52f2f05a181b9f971e1601fb782cd7b068815bf3115dc7bc6b4a36af"},
			ImageMusllinux1_2X86_64:  {Tag: "2025.09.19-1", Digest: "sha256:76b13f7cd0d83306366b8f0d6dd4fdf4450e3b2c1e937a0c5ddde6df8fd36d79"},
		},
	},
	{
		Version:   "3.2.1",
		Published: time.Date(2025, time.October, 12, 8, 24, 57, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2025.10.10-1", Digest: "sha256:9bc3d6107261c6d6bdd28512778d7b5c2d57f79f5baa5ad4a3533026e4a4237d"},
			ImageManylinux2_28X86_64: {Tag: "2025.10.10-1", Digest: "sha256:66eb5f6dadae4b343b4c22846adc27d2130ae753a7e59f7eb34de545422badd1"},
			ImageManylinux2_34X86_64: {Tag: "2025.10.10-1", Digest: "sha256:36180ba37fc0f54ed5a79af5debd5ee9a3d0720068c49297ab76245aa8daf8f0"},
			ImageMusllinux1_2X86_64:  {Tag: "2025.10.10-1", Digest: "sha256:70f61d95f380b394806df18950bc50477fd8f102cfbad384aab03aeac0bebe0f"},
		},
	},
	{
		Version:   "3.3.0",
		Published: time.Date(2025, time.November, 12, 19, 29, 2, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2025.11.09-2", Digest: "sha256:1003b8f156dcd9707bf1cb9f772178a37e35e4601e4e91547d1e4ba59addc99a"},
			ImageManylinux2_28X86_64: {Tag: "2025.11.09-2", Digest: "sha256:36887edfecddee55fee72cb68591d2f15e8f0daed9a3c6b176e3610f792f4c64"},
			ImageManylinux2_34X86_64: {Tag: "2025.11.09-2", Digest: "sha256:744b14152b41009fb4b6a29b9870d4566e12b66e2d36ada9bec2dd41085df9b5"},
			ImageMusllinux1_2X86_64:  {Tag: "2025.11.09-2", Digest: "sha256:e9ecee833bb67b785eaa695432b830a34563db13c19ee5c7775d865f42c539b5"},
		},
	},
	{
		Version:   "3.3.1",
		Published: time.Date(2026, time.January, 5, 19, 58, 16, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2026.01.04-1", Digest: "sha256:f405dbbc0396a0637614213002fdde8bea2be52b3155e1c366734e1fde930c81"},
			ImageManylinux2_28X86_64: {Tag: "2026.01.04-1", Digest: "sha256:4d62ce9d1ca259171e7cde403686e538e6f8fdc517660a557a66e102577d67d3"},
			ImageManylinux2_34X86_64: {Tag: "2026.01.04-1", Digest: "sha256:f4cf0b6ca26463dbaebdcc92af683ef6f37d710facf6c1914b30bd69fa2b4d5a"},
			ImageMusllinux1_2X86_64:  {Tag: "2026.01.04-1", Digest: "sha256:29a49865294878ede482106238a4b30190ef7825783bd8d15a43bd22f5ce874b"},
		},
	},
	{
		Version:   "3.4.0",
		Published: time.Date(2026, time.March, 5, 9, 2, 17, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2026.03.01-1", Digest: "sha256:fbbb6f1b0ab03a8fbfce39e979a6b10252ea525400430a4ffa6d88d68dded985"},
			ImageManylinux2_28X86_64: {Tag: "2026.03.01-1", Digest: "sha256:d5f19b5957cf25df7ac15465924cafe2358754a187e510af386bf9596598a372"},
			ImageManylinux2_34X86_64: {Tag: "2026.03.01-1", Digest: "sha256:e36baf9250643e8c521247a2eed8b9480237d9a0808b5d5e734de8cb2f21ca0c"},
			ImageMusllinux1_2X86_64:  {Tag: "2026.03.01-1", Digest: "sha256:37f0e89f9c6e66cde0807a6ca55967a8a7416b0012f0f4a7cd3054d00f79d360"},
		},
	},
	{
		Version:   "3.4.1",
		Published: time.Date(2026, time.April, 2, 13, 58, 59, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2026.03.20-1", Digest: "sha256:85939338c0689ccf4e1dbb6b5d632d106323f3e1993ed1cf8c096805b9cecb50"},
			ImageManylinux2_28X86_64: {Tag: "2026.03.20-1", Digest: "sha256:853663dc8253b62be437bb52a5caecffd020792af4442f55d927d22e0ea795ae"},
			ImageManylinux2_34X86_64: {Tag: "2026.03.20-1", Digest: "sha256:10eac5343b62488bf26046e74a4cdbaec1b76c468a0c9c0cb37fcf856fe475d5"},
			ImageMusllinux1_2X86_64:  {Tag: "2026.03.20-1", Digest: "sha256:5b6fe3ed82ff48748c5c528fc82e42674a5363890ed949923af65b0c5b5ef76c"},
		},
	},
	{
		Version:   "4.0.0",
		Published: time.Date(2026, time.June, 7, 18, 55, 19, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2026.06.04-1", Digest: "sha256:5e3012db7af44490157351ba6726fd92e8dba9b421ea819ac7925b4478ad3f17"},
			ImageManylinux2_28X86_64: {Tag: "2026.06.04-1", Digest: "sha256:d3f051574f040b4c1d23b18fd06741cd7288c6f537faa0a76b1c7edf048bfa62"},
			ImageManylinux2_34X86_64: {Tag: "2026.06.04-1", Digest: "sha256:280ca5d43f118a36210413053268ac75b0d4d0a538616ab6a47fa06b1da77b3a"},
			ImageMusllinux1_2X86_64:  {Tag: "2026.06.04-1", Digest: "sha256:fe194c488d56d0d48d9ca34ceab94772008a109e43a7b03b3d6ebf3a5744e3a7"},
		},
	},
	{
		Version:   "4.1.0",
		Published: time.Date(2026, time.June, 12, 16, 4, 1, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2026.06.04-1", Digest: "sha256:5e3012db7af44490157351ba6726fd92e8dba9b421ea819ac7925b4478ad3f17"},
			ImageManylinux2_28X86_64: {Tag: "2026.06.04-1", Digest: "sha256:d3f051574f040b4c1d23b18fd06741cd7288c6f537faa0a76b1c7edf048bfa62"},
			ImageManylinux2_34X86_64: {Tag: "2026.06.04-1", Digest: "sha256:280ca5d43f118a36210413053268ac75b0d4d0a538616ab6a47fa06b1da77b3a"},
			ImageMusllinux1_2X86_64:  {Tag: "2026.06.04-1", Digest: "sha256:fe194c488d56d0d48d9ca34ceab94772008a109e43a7b03b3d6ebf3a5744e3a7"},
		},
	},
	{
		Version:   "4.1.1",
		Published: time.Date(2026, time.July, 24, 20, 33, 17, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2026.07.19-1", Digest: "sha256:0d25b049964b2549b83384036abdff06789a8c0b1e9ff003ec80f0d531f79e50"},
			ImageManylinux2_28X86_64: {Tag: "2026.07.19-1", Digest: "sha256:a61875a2f84cab7df8de222ff12cabc08ff86eb4ad402ac90ba7bdaed9600cca"},
			ImageManylinux2_34X86_64: {Tag: "2026.07.19-1", Digest: "sha256:b6e1f264da7bf4e8db3e6a625ea1ecaf1e52290253df8588f71e4a9e50a85a17"},
			ImageMusllinux1_2X86_64:  {Tag: "2026.07.19-1", Digest: "sha256:fd0694e23637ae8d13433c58f647aba1aae5de4fd50350201307be453a8b2ff4"},
		},
	},
	{
		Version:   "4.2.0",
		Published: time.Date(2026, time.August, 5, 2, 25, 2, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2026.08.04-1", Digest: "sha256:c163a278006f45883c117b4166b93cdc7b574b62e58292ed9e52879579841d77"},
			ImageManylinux2_28X86_64: {Tag: "2026.08.04-1", Digest: "sha256:012f4a50472412f18bb2b450c1cce7158434cfae4ae878591c2748a13a30c2be"},
			ImageManylinux2_34X86_64: {Tag: "2026.08.04-1", Digest: "sha256:db817cd4c670f1191d74db6a94a0b115954af78861db7da660de4e93ebf2984c"},
			ImageMusllinux1_2X86_64:  {Tag: "2026.08.04-1", Digest: "sha256:f130bd3e3aebb39abcdec28a89f987f0d31b52d74bac5852318303698e9a5033"},
		},
	},
	{
		Version:   "4.2.1",
		Published: time.Date(2026, time.September, 5, 14, 47, 48, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2026.09.05-1", Digest: "sha256:493d2032114d757aaa761a9385ad8497f391503bf71acef9abeeb66682ca5d90"},
			ImageManylinux2_28X86_64: {Tag: "2026.09.05-1", Digest: "sha256:53390351aeb4688114b02c36a23b3e6ce1166ee9b7afc5df1a4f776354fc764c"},
			ImageManylinux2_34X86_64: {Tag: "2026.09.05-1", Digest: "sha256:934419fa742ff922855f464203cc0ad5afe3317a8541712a00cf3dc7fb893fc8"},
			ImageMusllinux1_2X86_64:  {Tag: "2026.09.05-1", Digest: "sha256:621f8004ed526a5a6bf6a866fb415ad8da54d59a991e50b3b69167c3a768a616"},
		},
	},
	{
		Version:   "4.3.0",
		Published: time.Date(2026, time.October, 5, 8, 18, 41, 0, time.UTC),
		Images: map[string]PinnedImage{
			ImageManylinux2014X86_64: {Tag: "2026.10.03-1", Digest: "sha256:ffd6d1f11237599748657996b750db6b3a5b724fea5a81cd9ea65add4f45b6c9"},
			ImageManylinux2_28X86_64: {Tag: "2026.10.03-1", Digest: "sha256:39df0042d5cc900b085aa25a0659368b42a0006c54c474299b785b44c1b4ff82"},
			ImageManylinux2_34X86_64: {Tag: "2026.10.03-1", Digest: "sha256:e4ca528d41ab66b3654110295d7a2c7bfa599ddbb6efb269ec21f7f73b88f1b6"},
			ImageMusllinux1_2X86_64:  {Tag: "2026.10.03-1", Digest: "sha256:ff786af69d772d7ac3e318c00a2b682428a352cc822d6175f6a0d4b431c0d44d"},
		},
	},
}
